server:
    port: 8091
spring:
    artemis:
        password: test
        user: test
        mode: native
        broker-url: tcp://artemis:61616

jws-rpc:
    #  name: j-ws-rpc-sample
    simulate: false
    packageName: uz.devcraft
    gateway: gateway
    microservice: microservice
    reactive: false

logging:
    level:
        root: info
        uz.devops: debug
        uz.devcraft: debug